### ISSUE TITLE
Get marketcrush installed in virtual environment

### ISSUE THREAD

**Issue by rodler** [basaks/marketcrush#1]
* Python version: 3.5
* Operating System: Ubuntu 14.04

### Description

Was not able to install marketcrush in virtenv because of issue with the Matplotlib backend Tk (_tkinter).

### What I Did

The official Matplotlib page for virtualenv:

 http://matplotlib.org/faq/virtualenv_faq.html

suggested the following, which worked for me.

```
pip install PySide
```

**Comment by basaks** [comment]
@rodler
Thanks for this. It has been addressed in the readme.
